### ISSUE TITLE
O site de vocês está ficando bacana

### ISSUE THREAD

**Issue by OdineiRibeiro** [FabricaAppU9/SiteOficial#12]
Se abrirem mão dos formulários de email em .php e usarem o google forms ou o type forms, dá para hospedar aqui no github mesmo

**Comment by gabrielbaptista** [comment]
Olá Odinei,

Obrigado pelo Feedback.

Passa lá na Fábrica, vamos conversar.

Abraço,

Prof. Gabriel.

**Comment by OdineiRibeiro** [comment]
Que horas vocês começam a trabalhar no sábado?

**Comment by gabrielbaptista** [comment]
Estamos por lá a partir das 8:00 - 8:30.

Sem mais,

Prof. Gabriel.
