### ISSUE TITLE
Procurar depoimento professor Nacif

### ISSUE THREAD

**Issue by BiancaArantes28** [FabricaAppU9/SiteOficial#25]

**Comment by FabricaAppU9** [comment]
Já mandei um e-mail para o professor Nacif para verificar como está o status do ProCalc

**Comment by FabricaAppU9** [comment]
Bianca, favor atualizar o site:
"Temos grande alegria e enorme prazer mantermos o contato e acompanhar a evolução do software. É um sonho de décadas, agora se concretizando graças ao empenho
de tão brilhante grupo da Fábrica de App da Uninove, que aceitaram o desafio de algo tão diferente e tendo à frente o Prof. Gabriel."

**Comment by FabricaAppU9** [comment]
Bianca, agora é com você

**Comment by BiancaArantes28** [comment]
Já coloquei o depoimento lá no site. Vou fechar a tarefa, qualquer problema, por favor, entre em contato. Obrigada!
