### ISSUE TITLE
Criar conteúdo para YouTube do Projeto

### ISSUE THREAD

**Issue by FabricaAppU9** [FabricaAppU9/SiteOficial#28]
A ideia do canal é distribuir conteúdo sobre como uma pessoa interessada pode construir aplicativos, obviamente convidando as pessoas a virem estudar na UNINOVE.

**Comment by Deborauni9** [comment]
Poderíamos fazer um vídeo curto com nossos alunos. 3 min. 
Depois faríamos outros mostrando a rotina da Fábrica de Aplicativos.

**Comment by gabrielbaptista** [comment]
Débora, isso está na nossa estratégia.

Precisamos montar os vídeos e encaminhar ao professor Bussab antes de
publicar, ok?


2016-12-07 14:12 GMT-02:00 Deborauni9 <notifications@github.com>:

**Comment by Deborauni9** [comment]
Blz. claro.

Em 8 de dez de 2016 12:54 PM, "gabrielbaptista" <notifications@github.com>
escreveu:

**Comment by gabrielbaptista** [comment]
:) Realmente pensei que você tinha postado!

**Comment by GuilhermeFujita** [comment]
Tarefa cancelada
