### ISSUE TITLE
Cotas Camisetas

### ISSUE THREAD

**Issue by FabricaAppU9** [FabricaAppU9/SiteOficial#6]

**Comment by josejuniorcj** [comment]
Vanessa, achei uma loja legal na Paulista. 

http://www.camisetasem12h.com.br/orcamento-camisetas-personalizadas/

Vê e me diz o que acha..

**Comment by FabricaAppU9** [comment]
Qual o valor que vocês conseguiram?
Conseguem apresentar um valor no próximo sábado?

**Comment by josejuniorcj** [comment]
Irei pegar os tamanhos corretos e no próximo sábado já tenho um valor aproximado.

**Comment by BiancaArantes28** [comment]
Acho que por enquanto não vamos mais fazer isso
